# Generated by Django 5.1.6 on 2025-03-11 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paintworks', '0003_alter_carritoitem_productos_datos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carritoitem',
            old_name='productos',
            new_name='producto_id',
        ),
    ]
