# Generated by Django 5.1.6 on 2025-03-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paintworks', '0004_rename_productos_carritoitem_producto_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carritoitem',
            old_name='producto_id',
            new_name='producto',
        ),
    ]
