# Generated by Django 5.1.7 on 2025-03-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paintworks', '0005_rename_producto_id_carritoitem_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordenitem',
            old_name='productos',
            new_name='producto',
        ),
    ]
