# Generated by Django 5.0.13 on 2025-03-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintworks', '0006_rename_productos_ordenitem_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
    ]
